### ISSUE TITLE
It should indicate the current branch when opening

### ISSUE THREAD

**Issue by nwinkler** [ruyadorno/git-bc#3]
When starting `git bc`, it should somehow indicate the currently active branch, e.g. using a different color - or even making it the default selection. Right now, it's simply defaulting to the first branch. If you don't have a branch indicator in your current prompt, it's hard to tell what branch you're currently on.

**Comment by ruyadorno** [comment]
git uses a `*` to indicate the current branch on `git branch`, I'll try to change the current behavior to preserve this indicator.

in the current version all branch names are being cleaned up before invoking the interactive listing
